services:
  personal-site-nginx:
    image: docker.m.daocloud.io/library/nginx:1.27-alpine
    container_name: personal-site-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
